steps:
  - label: ":docker: Publish to ECR"
    command: |
      echo "~~~ :key: Logging In"
      aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/automattic
      echo "~~~ :hammer: Building Image"
      docker build -t android-build-image .
      # If a tag is present use it
      if [ -n "$BUILDKITE_TAG" ]; then
        echo "~~~ :label: Tagging Image with version $BUILDKITE_TAG"
        docker tag android-build-image:latest public.ecr.aws/automattic/android-build-image:$BUILDKITE_TAG
        echo "~~~ :arrow_up: Pushing Image"
        docker push public.ecr.aws/automattic/android-build-image:$BUILDKITE_TAG
        exit 0
      fi
      if [ $BUILDKITE_BRANCH = "trunk" ]; then
        echo "~~~ :label: Tagging 'latest' version"
        docker tag android-build-image:latest public.ecr.aws/automattic/android-build-image:latest
        echo "~~~ :arrow_up: Pushing Image"
        docker push public.ecr.aws/automattic/android-build-image:latest
        exit 0
      fi
      if [ -n "$BUILDKITE_COMMIT" ]; then
        echo "~~~ :label: Tagging Image with commit $BUILDKITE_COMMIT"
        docker tag android-build-image:latest public.ecr.aws/automattic/android-build-image:$BUILDKITE_COMMIT
        echo "~~~ :arrow_up: Pushing Image"
        docker push public.ecr.aws/automattic/android-build-image:$BUILDKITE_COMMIT
        exit 0
      fi
      echo "Unable to publish image"
      exit 1
